[target.aarch64-linux-android]
ar = "llvm-ar"
linker = "aarch64-linux-android34-clang"

[target.armv7-linux-androideabi]
ar = "llvm-ar"
linker = "armv7-linux-androideabi34-clang"

[target.x86_64-linux-android]
ar = "llvm-ar"
linker = "x86_64-linux-android34-clang"
